basePath: /api/v1
definitions:
  controller._ResponsePostList:
    properties:
      code:
        description: 业务响应状态码
        type: integer
      data:
        description: 数据
        items:
          $ref: '#/definitions/models.ApiPostDetail'
        type: array
      message:
        description: 提示信息
        type: string
    type: object
  models.ApiPostDetail:
    properties:
      author_id:
        type: integer
      author_name:
        type: string
      community_id:
        type: integer
      content:
        type: string
      create_time:
        description: time.Time 需要连接的时候增加parseTime=true
        type: string
      id:
        type: integer
      introduction:
        type: string
      name:
        type: string
      post_id:
        type: integer
      status:
        type: integer
      title:
        type: string
      update_time:
        type: string
    required:
    - community_id
    - content
    - title
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: support@swagger.io
    name: 这里写联系人信息
    url: http://www.swagger.io/support
  description: 这里写描述信息
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 这里写标题
  version: "1.0"
paths:
  /posts2:
    get:
      consumes:
      - application/json
      description: 可按社区按时间或分数排序查询帖子列表接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 可以为空
        example: 1
        in: query
        name: communityID
        type: integer
      - description: 排序依据
        example: score
        in: query
        name: order
        type: string
      - description: 页码
        example: 1
        in: query
        name: page
        type: integer
      - description: 每页数据量
        example: 10
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponsePostList'
      security:
      - ApiKeyAuth: []
      summary: 升级版帖子列表接口
      tags:
      - 帖子相关接口
swagger: "2.0"
