name: "web_app"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time: "2022-10-01"
machine_id: 1

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  db_name: "bluebell"
  max_open_conns: 200
  max_idle_conns: 20

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100